### ISSUE TITLE
Use pager even when output fits in single page

### ISSUE THREAD

**Issue by VanushVaswani** [ymattw/cdiff#57]
cdiff is a great tool, but one minor annoyance is when using cdiff and expecting multiple pages, often have to press "Ctrl-D" to scroll. One side effect is when there is a single page output, the pager prompt is missing, so "Ctrl-D" will often log out of the terminal (or in my case, tmux pane).

Feature request would be to ensure prompt is available for all page lengths so Ctrl-D will not inadvertently log out of the terminal session.

**Comment by ymattw** [comment]
That behavior is to keep compatible with git diff, if the diff can be fit in one window than pager is not needed.

Do you know you can scroll down a half-window is to press `d` instead of `^D`, and press `SPACE` or `f` to scroll down one window?

If you can't change your habit, you can set environment variable `LESS` to override the behavior, that variable provides default options to `less(1)`, it's default to `-FRSX --shift 1` in cdiff code.  For example, `alias d="LESS='-RSX --shift 1' cdiff"` (remove the `-F` flag to always show the pager).
