### ISSUE TITLE
Add support for configuration file

### ISSUE THREAD

**Issue by Muffo** [ymattw/cdiff#59]
I use `cdiff` everyday and 99% of the time in side by side mode.

It would be very nice if the application automatically picked up the user preferences from an `.cdiffrc` file so I would not have to explicitly add the `-s` option every time.

What do you think?

**Comment by ymattw** [comment]
Hello, thanks for your interest!

There are many ways to fulfill your request:

1. Use a shell alias
2. Use a wrapper script
3. Introduce an environment variable (e.g. CDIFFOPT), same as how LESS works for less
4. Introduce a .cdiffrc config file (and also /etc/cdiffrc).

I would say they actually all are adding some kinds of configuration. #1 and #2 do not require change to cdiff, if they work for you I'd keep cdiff minimal but functional.  If they don't I personally prefer to #3 since it's more simple and natural.  I may work on this later, pull request is very welcome. Thanks!

**Comment by Muffo** [comment]
Thanks for all the suggestions!
The alias could probably work well in my case.

**Comment by ymattw** [comment]
@Muffo I have implemented a `CDIFF_OPTIONS` environment variable to hold the default options, would you help validate the usage? Thanks.

**Comment by Muffo** [comment]
I have installed the latest version of cdiff from the repository and the environment variable works as expected!!

Thanks a lot!!
